language: r
sudo: false
dist: trusty

os:
  - linux
  - osx
  - windows
  
latex: true

warnings_are_errors: false

cache: packages
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'library(covr); codecov()'
